/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_F103_x6.h"
#include "Stm32_F103C6_GPIO_Drivers.h"

void clock_init()
{

	//enable clock  GPIOA
	RCC_GPIOA_CLK_EN();
	//enable clock GPIOB
	RCC_GPIOB_CLK_EN();

}
void gpio_init()
{
	GPIO_Pinconfig_t pincfg;
	//PA1: input Highz floating input(reset value)
	pincfg.GPIO_PinNumber =GPIO_PINS_1;
	pincfg.GPIO_MODE =GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &pincfg);

	//PB1 :(OUTPUT push pull mode)
	//01 :output mode ,max speed=10MHZ
	//CNF 00 :General purpose ouput push pull
	pincfg.GPIO_PinNumber =GPIO_PINS_1;
	pincfg.GPIO_MODE =GPIO_MODE_OUTPUT_PP;
	pincfg.GPIO_OUTPUT_SPEED =GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &pincfg);


	//PA13: input Highz floating input(reset value)
	pincfg.GPIO_PinNumber =GPIO_PINS_13;
	pincfg.GPIO_MODE =GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &pincfg);

	//PB13 :(OUTPUT push pull mode)
	//01 :output mode ,max speed=10MHZ
	//CNF 00 :General purpose ouput push pull
	pincfg.GPIO_PinNumber =GPIO_PINS_13;
	pincfg.GPIO_MODE =GPIO_MODE_OUTPUT_PP;
	pincfg.GPIO_OUTPUT_SPEED =GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &pincfg);



}
void wait(int x)
{
	int  i,j;
	for(i = 0; i < x; i++)
		for(j=0; j < 255; j++);
}
int main(void)
{

	clock_init();
	gpio_init();
	while(1)
	{
		//PA1 : connected external PUR
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PINS_1) == 0 )  //press A1
		{

			MCAL_GPIO_togglePin(GPIOB, GPIO_PINS_1);
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PINS_1) == 0); //single pressing
		}

		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PINS_13) == 1)    //press A13 (PDR)
		{

			MCAL_GPIO_togglePin(GPIOB, GPIO_PINS_13);
			//multiple pressing
		}
		wait(1);
	}




}
